name = "turso-prisma-cloudflare-workers"
compatibility_date = "2023-12-01"
node_compat = true

[vars]
TURSO_DATABASE_URL = ""
TURSO_DATABASE_AUTH_TOKEN = ""

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
